### ISSUE TITLE
linux-bede-lts and Steam

### ISSUE THREAD

**Issue by Xeers** [herecura/linux-bede-lts#1]
I can not boot the Steam gaming platform with the linux-bede or linux-bede-lts  4.14.50-1 kernels (I do not have this problem with other kernels: Arch, linux-zen, linux-lts ...).
"Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6"

pacman -Qo /usr/lib/libc.so.6
/usr/lib/libc.so.6 está contenido en glibc 2.27-3

ls -l /usr/lib32/libc.so.6
lrwxrwxrwx 1 root root 12 may  2 22:10 /usr/lib32/libc.so.6 -> libc-2.27.so

ls -l /usr/lib32/libc-2.27.so
-rwxr-xr-x 1 root root 2191264 may  2 22:10 /usr/lib32/libc-2.27.so

sudo ldconfig
ldconfig -p | grep libc.so.6
	libc.so.6 (libc6,x86-64, ABI del SO: Linux 3.2.0) => /usr/lib/libc.so.6
	libc.so.6 (ELF, ABI del SO: Linux 3.2.0) => /usr/lib32/libc.so.6

ls -ld /
drwxr-xr-x 19 magpieos 1001 4096 jun 13 11:30 /

ls -l ~/.local/share/Steam/ubuntu12_32/steam
-rwxr-xr-x 1 magpieos magpieos 4798782 jun  9 01:39 /home/magpieos/.local/share/Steam/ubuntu12_32/steam

chmod 777 .local/share/Steam/ubuntu12_32/steam
ls -l .local/share/Steam/ubuntu12_32/steam
-rwxrwxrwx 1 magpieos magpieos 4798782 jun  9 01:39 .local/share/Steam/ubuntu12_32/steam
.local/share/Steam/ubuntu12_32/steam
bash: .local/share/Steam/ubuntu12_32/steam: cannot execute binary file: Formato de ejecutable incorrecto

ls -l /usr/lib/ld-linux*
lrwxrwxrwx 1 root root 22 may  2 22:10 /usr/lib/ld-linux.so.2 -> ../lib32/ld-linux.so.2
lrwxrwxrwx 1 root root 10 may  2 22:09 /usr/lib/ld-linux-x86-64.so.2 -> ld-2.27.so
I have installed: linux-bede-lts, linux-bede-lts-headers, nvidia-bede-lts, broadcom-wl-bede-lts (My graphics card is Nvidia). Installing nvidia-bede-lts uninstalls nvidia-dkms (linux-zen needs nvidia-dkms).

Install nvidia-390xx-bede-lts 390.67-3 ?
"the dependencies could not be satisfied:
delete nvidia-utils breaks the dependency 'nvidia-utils = 396.24' required by nvidia-bede-lts
delete nvidia-utils breaks the dependency 'nvidia-utils = 396.24' required by nvidia-lts".

dkms installed.

Install nvidia-dkms, this uninstalls nvidia-bede-lts

What do I have to do to make Steam work with linux-bede-lts and proprietary Nvidia drivers?

**Comment by BlackIkeEagle** [comment]
Sorry, none of my kernels support 32bit multilib. All are compiled 64bit only.

**Comment by Xeers** [comment]
My CPU is an AMD octacore and I use MagpieOS (64 bits). Can not do anything then?

**Comment by BlackIkeEagle** [comment]
If you *really* want to try this kernel you could rebuild it with 32bit support

https://github.com/herecura/linux-bede-lts/blob/herecura/config-desktop.x86_64#L858

**Comment by Xeers** [comment]
ok, thanks
